#!/bin/sh
OLD_JAVA_HOME=$JAVA_HOME
OLD_PATH=$PATH
export JAVA_HOME=`pwd`/jre1.8.0_31.jre/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH
./bin/zans-story
export JAVA_HOME=$OLD_JAVA_HOME
export PATH=$OLD_PATH
